@ECHO OFF
TITLE Creating Folders Program
::CHCP 65001
::CLS
SET EXERCISE=exercise
SET /A START_NUM=120
SET /A END_NUM=122
SET /A STEP_NUM=1
:: LOOP FROM START_NUM TO STOP_NUM BY STEP_NUM.
FOR /L %%I IN (%START_NUM%, %STEP_NUM%, %END_NUM%) DO (
	MKDIR %EXERCISE%%%I
)
ECHO TO CREATE FOLDERS FROM %EXERCISE%%START_NUM% TO %EXERCISE%%END_NUM%
::PAUSE > NUL
::PAUSE
EXIT