@ECHO OFF
TITLE Creating Folders Program
::CHCP 65001
::CLS
SET FOLDER_NAME=exercise
SET FILL=0
SET /A START_NUM=1
SET /A STEP_NUM=1
SET /A END_NUM=15
:: LOOP FROM START_NUM TO STOP_NUM BY STEP_NUM.
FOR /L %%I IN (%START_NUM%, %STEP_NUM%, %END_NUM%) DO (
	IF %%I LSS 10 (
		MKDIR %FOLDER_NAME%%FILL%%%I
	) ELSE (
		MKDIR %FOLDER_NAME%%%I
	)
)
IF /A %START_NUM% LSS 10 (
	ECHO TO CREATE FOLDERS FROM %FOLDER_NAME%%FILL%%START_NUM% TO %FOLDER_NAME%%END_NUM%
) ELSE (
	ECHO TO CREATE FOLDERS FROM %FOLDER_NAME%%START_NUM% TO %FOLDER_NAME%%END_NUM%
)

::PAUSE > NUL
::PAUSE
EXIT